server:
  port: 8120
spring:
  application:
    name: "file-service"
  config:
    import: "optional:configserver:http://localhost:8071/"

#config upload file
  servlet:
    multipart:
      #default = 1MB
      max-file-size: 5MB
      #default = 10 MB (form data)
      max-request-size: 50MB

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

app:
  upload-file:
    base-uri: file:///D:/upload/
  services:
    auth: http://localhost:8080


info:
  app:
    name: "file-service"
    description: "JobHunter Company Application"
    version: "1.0"

logging:
  level:
    com:
      tuananh:
        fileservice: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
