server:
  port: 8110
spring:
  application:
    name: "resume-service"
  #  profiles:
  #    active: native
  datasource:
    url: jdbc:mysql://localhost:3309/resumesdb
    username: root
    password: ""
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

app:
  services:
    auth: http://localhost:8080
    company: http://localhost:8090
    job: http://localhost:8100

info:
  app:
    name: "resume-service"
    description: "JobHunter Company Application"
    version: "1.0"
